name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/movieflix
  NODE_VERSION: 18

jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Build da imagem Docker
        run: docker build -t ${{ env.DOCKER_IMAGE }}:latest .
      
      - name: Salvar imagem Docker
        run: |
          docker save ${{ env.DOCKER_IMAGE }}:latest -o movieflix-image.tar
      
      - name: Upload da imagem
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: movieflix-image.tar

  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:

      - name: Download da imagem
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Carregar imagem Docker
        run: docker load -i movieflix-image.tar
      
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      

      - name: Tag da imagem
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:latest ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          docker tag ${{ env.DOCKER_IMAGE }}:latest ${{ env.DOCKER_IMAGE }}:latest
      

      - name: Push para Docker Hub
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          echo "Imagem publicada no Docker Hub!"
